name: Build and Push Docker Image to Github Registry

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'packages/Dockerfile'
      - '.github/**'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number to tag (git and docker image)'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set lowercase image name
        run: |
          echo "IMAGE_LOWER=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "BRANCH_NAME=$(echo '${{ github.ref }}' | sed 's|refs/[^/]*/||g' | tr '/' '-')" >> $GITHUB_ENV

      - name: Check if tag exists on remote
        if: github.event.inputs.version != ''
        run: |
          if git ls-remote --tags origin "${{ github.event.inputs.version }}" | grep -q "${{ github.event.inputs.version }}"; then
            echo "Tag ${{ github.event.inputs.version }} already exists on the remote."
            exit 0
          fi
      
      - name: Create and push Git tag
        if: github.event.inputs.version != ''
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git tag -a "${{ github.event.inputs.version }}" -m "Release ${{ github.event.inputs.version }}"
          git push origin "${{ github.event.inputs.version }}"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packages/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_LOWER }}:latest
            ghcr.io/${{ env.IMAGE_LOWER }}:${{ env.BRANCH_NAME }}
            ghcr.io/${{ env.IMAGE_LOWER }}:${{ github.sha }}
            ${{ github.event.inputs.version && format('ghcr.io/{0}:{1}', env.IMAGE_LOWER, github.event.inputs.version) || '' }}